### PR TITLE
Major refactor

### PR DESCRIPTION
**Pull request by marsolk**
I should've broken this up but that's not how my brain works.

Short version:
* `albw` split into `game` (basic game information) and `rom` (reading and manipulating game files)
* moved `settings` into new `modd` crate, containing common types needed by both randomizer and patcher
* split `patcher` into its own crate, separate from `randomizer`
* several types and whatnot moved around and renamed to wherever and whatever I felt was most appropriate (or what worked)
* small reorganization of files and directories

### CODE REVIEW

**Comment by marsolk** [comment]
Changed, but there's conflicts I can't resolve. Maybe a `0.4` branch or a `dev` branch to develop against?

**Comment by rickfay** [comment]
Hmm... can you `rebase`? It's newly branched off from `master`, the only change is I bumped the version numbers from v0.3.1 to v0.3.2.

**Comment by rickfay** [comment]
I'm giving some thought to creating a `dev` branch

**Comment by rickfay** [comment]
Mkay I created a `dev` branch and pointed this PR at it, am going to try to get the review done tonight

**Review by rickfay — COMMENTED** [review]
So first, thanks for submitting this! Sorry for taking a while to review this, but I really appreciate the contribution and I like a lot of what I'm seeing here.

I left comments in the individual files, but some general ones here:
- You mentioned Hints weren't working with this, need to get those working before I can accept anything.
- Using `strum` is interesting but we need separate serialization strategies for items as they appear in the Spoiler Log as well as in in-game Hints. I need to think about this one more.
- Not sure why you removed the Color information for Regions?
- Replacing the `fail` macro with more explicit error handling is something I did want to do and I'm glad to see it, but couple things:
  - I had wanted to cleanly differentiate between errors that are and aren't retryable
  - This needs _a lot_ of testing
- I'm using `rustfmt` to handle formatting the code, looks like you're using something else. I'm open to suggestions if you think there's a better option?
- There's a number of things here that conflict with the refactor I'm separately working on, mostly around the `modd` crate.

Altogether, I don't think I can merge in these changes. In addition to the above, there's just a lot going on that needs testing and/or design discussion (taking into account the other refactor) before I can accept it. I'd request breaking this PR up into smaller ones.

**Pull request closed without merging**
